name: Scraper de Legisladores

on:
  schedule:
    # Ejecutar cada semana los lunes a las 9:00 AM
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Permitir ejecución manual

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas
        
    - name: Run scraper
      run: python scraper_legiscaba.py
      env:
        OBTENER_DETALLES: ${{ github.event_name == 'workflow_dispatch' || github.run_number == 1 }}
        
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Actualización automática de datos: $(date +%Y-%m-%d)" && git push)